package com.github.ryutaro.core_designsystem.theme

import androidx.compose.ui.graphics.Color

// Light color
val LightPrimary = Color(0xFF006e2c)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF68ff8a)
val LightOnPrimaryContainer = Color(0xFF002108)
val LightSecondary = Color(0xFF5f52a7)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFe5deff)
val LightOnSecondaryContainer = Color(0xFF1a0261)
val LightTertiary = Color(0xFF39656c)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFbdeaf3)
val LightOnTertiaryContainer = Color(0xFF001f24)
val LightError = Color(0xFFba1a1a)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFffdad6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFFFFFF)
val LightOnBackground = Color(0xFF000000)
val LightSurface = Color(0xFFfcfdf7)
val LightOnSurface = Color(0xFF1a1c19)
val LightOutline = Color(0xFF727970)
val LightSurfaceVariant = Color(0xFFdde5d9)
val LightOnSurfaceVariant = Color(0xFF424940)

// Dark color
val DarkPrimary = Color(0xFF32e36a)
val DarkOnPrimary = Color(0xFF003913)
val DarkPrimaryContainer = Color(0xFF00531f)
val DarkOnPrimaryContainer = Color(0xFF68ff8a)
val DarkSecondary = Color(0xFFc9bfff)
val DarkOnSecondary = Color(0xFF302175)
val DarkSecondaryContainer = Color(0xFF473a8d)
val DarkOnSecondaryContainer = Color(0xFFe5deff)
val DarkTertiary = Color(0xFFa1ced6)
val DarkOnTertiary = Color(0xFF00363d)
val DarkTertiaryContainer = Color(0xFF1f4d54)
val DarkOnTertiaryContainer = Color(0xFFbdeaf3)
val DarkError = Color(0xFFffb4ab)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000a)
val DarkOnErrorContainer = Color(0xFFffdad6)
val DarkBackground = Color(0xFF1a1c19)
val DarkOnBackground = Color(0xFFe2e3dd)
val DarkSurface = Color(0xFF1a1c19)
val DarkOnSurface = Color(0xFFe2e3dd)
val DarkOutline = Color(0xFF8b9389)
val DarkSurfaceVariant = Color(0xFFc1c9be)
val DarkOnSurfaceVariant = Color(0xFFc1c9be)